### ISSUE TITLE
Client synchronizes top level files when they were not included

### ISSUE THREAD

**Issue by koreywithak** [nextcloud/client_updater_server#11]
With version 2.2.4 (build 2) of the Nextcloud Windows Desktop Client synchronization tool, I have noticed that if I add a connection and add a folder sync at the same time, no matter what subdirectory I choose to synchronize, it also synchronizes the top level files (not folders) as well. However, if I simply create the connection and skip folder sync and go to add folder sync at a later time, when I set up the same subfolder synchronization, it correctly does not include the top level files. I have server version 10.0.1 running Jessie Lite, nginx 1.10, php 7.0, and mariadb 10.0.

**Comment by rullzer** [comment]
Yes this is intended behaviour the list is an exclude list, not an include list.
