### ISSUE TITLE
Does this even work, or is it just unmaintained?

### ISSUE THREAD

**Issue by enoch85** [nextcloud/client_updater_server#12]
Ask the subject --^

Never get update notifications, that's why I'm asking.

**Comment by nickvergessen** [comment]
Should work, but https://github.com/nextcloud/client_updater_server/blob/master/config/config.php is missing the latest versions, so no update prompting.

**Comment by nickvergessen** [comment]
Missing windows client update:
https://github.com/nextcloud/client_updater_server/pull/13
