### ISSUE TITLE
Take into account operating server info to scope updates to supported ones

### ISSUE THREAD

**Issue by mgallien** [nextcloud/client_updater_server#129]
Given the changes in macOS limiting our ability to support old macOS releases, we need to make sure we do not distribute unsupported release of desktop client to releases unable to install or run it.
Similarly, when we manage to release a desktop client version based on Qt6, we will also have to bump the platform requirements on most operating systems.
Then, we need to ensure we do not send an update based on Qt6 on operating system that are unsupported.
See https://doc-snapshots.qt.io/qt6-6.6/supported-platforms.html#desktop-platforms

**Comment by tobiasKaminsky** [comment]
What information needs to be send by client?
What do we need to change on updater server?

**Comment by mgallien** [comment]
on windows we would send those info to the updater server:
`platform=win32&osRelease=windows&osVersion=10&kernelVersion=10.0.19045&currentArch=x86_64`
that would allow to match the windows release and decide if the update is compatible with it
we just need to find out the kernel version matching the releases of windows 10 that we will be compatible with
on linux:
`platform=linux&osRelease=debian&osVersion=unknown&kernelVersion=6.6.15-amd64&currentArch=x86_64`
that will be definitely more messy as you can see

as indicated in my previous link, the requirements are the following:
Windows 10 (1809 or later) or any windows 11
macOS 11, 12, 13
Ubuntu 22.04 or openSUSE 15.5 or RHEL 8.6, 8.8, 9.2

**Comment by tobiasKaminsky** [comment]
https://sparkle-project.org/documentation/publishing/

add sparkle:minimumSystemVersion and sparkle:maximumSystemVersion for Sparkle

**Comment by tobiasKaminsky** [comment]
For Windows we have following osVersions:
QT5:
- 7 
- 7sp1
- 8
- 8.1

QT5/6, check build number: 
- 10
- 10sp1
- 10sp4

QT6:
- 11

Uncertain:
server2008r2
server2008r2sp1
server2012
server2012r2
server2016
server2016sp1
server2019
server2022
unknown

**Comment by tobiasKaminsky** [comment]
Mac is easy:
QT5: <11
QT6: >=11

**Comment by tobiasKaminsky** [comment]
Updated doc: https://doc.qt.io/qt-6/supported-platforms.html
