### ISSUE TITLE
Missing documentation and requirements

### ISSUE THREAD

**Issue by oparoz** [nextcloud/client_updater_server#14]
The XML PHP extension is a requirement, but it's not documented anywhere.
We're also missing information on which file and what exactly needs to be changed in order to properly configure and updater server.

**Comment by nickvergessen** [comment]
There is a file named `config/config.php` which suggests to be the configuration file.

**Comment by rullzer** [comment]
Maybe also add that they need a webserver :speak_no_evil:

**Comment by oparoz** [comment]
> There is a file named config/config.php which suggests to be the configuration file

Yes, but it requires looking for that info and it doesn't say what should be changed, etc.
We don't need a 10 page paper, just some simple instructions to make it easier for customers.

Maybe @MariusBluem could put something together?
