### ISSUE TITLE
Nextcloud update notification to 2.3.2 but download only 2.3.1 instead.

### ISSUE THREAD

**Issue by OlivierS1** [nextcloud/client_updater_server#17]
I don't know if it is the proper issue reporting area, but I am getting notification from my Nextcloud Client on Windows that a new version of the client is available

![image](https://user-images.githubusercontent.com/20311003/29137523-6b434ede-7cf5-11e7-86c5-abc11e99e74d.png)

However upon pressing the "Get update" button, I am redirected to the https://nextcloud.com/install/#install-clients webpage where only 2.3.1.8 is made available.

Any comments?

**Comment by nickvergessen** [comment]
Yeah website will be updated tonight

**Comment by nickvergessen** [comment]
Find the new version here https://download.nextcloud.com/desktop/releases/Windows/

**Comment by nickvergessen** [comment]
Fixed in the meantime
