### ISSUE TITLE
Update latest versions to 2.5 for the new client

### ISSUE THREAD

**Issue by e-alfred** [nextcloud/client_updater_server#24]
Hello,

currently no new updates for the 2.5 client are pushed to the users so they aren't notified of a new update of the client. This is very problematic because users still run outdated and potentially insecure versions of the Nextcloud desktop client without ever noticing.

**Comment by e-alfred** [comment]
@MorrisJobke @rullzer Can you help with this problem? It basically keeps people running extremely outdated clients with security vulnerabilities therefore pushing new releases to all clients should be a priority.

**Comment by MorrisJobke** [comment]
cc @camilasan as well.

We talked about this recently. Is there any news about this? Is it safe to push new versions out?

**Comment by DjSni** [comment]
really, you need over 8 months to decide if the users should get autoupdates or not. Finally unlock the updates and everyone is happy!

**Comment by splitt3r** [comment]
I think this one is fixed by https://github.com/nextcloud/client_updater_server/pull/27 isn't it?

**Comment by misch7** [comment]
Yepp, this has been solved. Just waited for users confirmation that it works before I close this one here 😼 

For details see: https://github.com/nextcloud/desktop/issues/927#issuecomment-538642639
