### ISSUE TITLE
No informatiom, clients not updating

### ISSUE THREAD

**Issue by jonathanmmm** [nextcloud/client_updater_server#25]
Hi,
I searched the Internet and I don't know what to do. Do I have to install this on my server? Are the desktop clients are looking into exactly this github repository? How can I make the clients show that there is an Update available. Going from client to client and updating through downloading newest version and installing is what this Update server makes not necessary, right?

Is this maintained? Do I have install it under the same url with a subdirectory, like mynextcloud.com/update _server? Can't find any information :/

Please help

**Comment by splitt3r** [comment]
Were you able to find the needed information? I think this code is deployed to a central Nextcloud update server. You can find the url somewhere in the desktop client code. As of now the client should show the latest 2.6 update on Linux + Windows. With macOS to come.

**Comment by misch7** [comment]
If you want to run your own update server for modified clients, this would be the right repo to use. Then you'd also have to modify the update server URL define in the client's code / set the environment variable for compilation.

For technical details see: https://github.com/nextcloud/desktop/issues/927#issuecomment-538642639

If you just run the unmodified client from our download site, you don't have to modify or host anything, update notifications are now working again :-)
