### ISSUE TITLE
Update latest versions to 3.0 for the new client

### ISSUE THREAD

**Issue by e-alfred** [nextcloud/client_updater_server#40]
@misch7 Can you add the 3.0 version to the updater so people get a notification that a new version is available?

**Comment by misch7** [comment]
@er-vin Do you think we are safe enough to do this with 3.0.1? (Thinking of nextcloud/desktop#2282)?

**Comment by er-vin** [comment]
@misch7 I looked at the diff between rc1 and 3.0.0 and there's no particular reason for that crash... well only thing which could come to mind is commit e02be629bb. As long as we don't get a backtrace or more information we won't be able to fix it anyway.

**Comment by misch7** [comment]
Oki doki, then let's rollout :)

Done with #41
