### ISSUE TITLE
[Windows Client] No longer starting at boot after update

### ISSUE THREAD

**Issue by plrunner** [nextcloud/client_updater_server#9]
Hi,
I open the Issue here. I do not know anywhere else.
The last update of my windows clients caused the option "start on boot" to get unchecked.

This happened on both windows 7 and windows 10 (no win8 on my field).

Regards
PL

**Comment by nickvergessen** [comment]
Can you reenable it again?
Basically we just change images, so not sure if it can be caused by us.

**Comment by plrunner** [comment]
Yes I can enable it again.
The problem is my users have been working out-of-sync for serveral days and they messed up the data. Very very nasty.
PL

**Comment by plrunner** [comment]
BTW, do you when the next client release is due to be released?
Thanks
PL

**Comment by nickvergessen** [comment]
Not sure if this can be caused by us. I don't really think so, but @rullzer should know more.

**Comment by rullzer** [comment]
Should not this is just the new binaries.
