### ISSUE TITLE
Deskop does not offer 3.6.0 stable

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/client_updater_server#96]
<img width="720" alt="2022-09-27 09_26_17-Nextcloud-Einstellungen" src="https://user-images.githubusercontent.com/1315170/192461247-842136dc-a53e-4694-85b5-2ae989c77c15.png">

Updater tells me no new version while I obviously run an RC and the final 3.6.0 is out since days.

By @AndyScherzinger

**Comment by tobiasKaminsky** [comment]
@mgallien what platform is used on win64?

**Comment by tobiasKaminsky** [comment]
Hm.
Seems to be win32:
https://github.com/nextcloud/desktop/blob/9dd9c464936ca5003240531bd45c8f2dc6032415/src/gui/updater/updater.cpp#L82

**Comment by allexzander** [comment]
Ahh, nevermind. The URL always returns x64 MSI anyways.

**Comment by tobiasKaminsky** [comment]
@AndyScherzinger can you click on "check update" and send us the logs?

**Comment by allexzander** [comment]
![image](https://user-images.githubusercontent.com/12224014/192489852-136cbdca-505f-4523-8001-31ccaf8e2c86.png)
Works for me.

@AndyScherzinger Kindly attach your **nextcloud.cfg** file from **C:\Users\YOUR-USER-NAME\AppData\Roaming\Nextcloud**.

Likely you've already seen the updated but clicked "Cancel" or something, and this got written to your cfg file.

**Comment by tobiasKaminsky** [comment]
> And yes, the channel must be `Stable`.

Beta should also give latest stable 3.6.0.
And then if 3.7.0RC1 is available, it should give this.

With above curl request you see that also with beta channel 3.6.0 is offered.

**Comment by mgallien** [comment]
this is in fact a desktop client bug that is going to be fixed by https://github.com/nextcloud/desktop/pull/4979
